### PR TITLE
Fix: Server crash after second user joined

### PR DESCRIPTION
**Pull request by CapsE**
Fixed an error where the server would crash after a second user joined a room.

### CODE REVIEW

**Comment by AlphaHinex** [comment]
Nice job!
But too many files changed in this PR and they are useless. The only valuable change is in `sockets.js`. Maybe you need to clean up before merge.

**Comment by CapsE** [comment]
Yeah sorry about that. I think my changes might have been wrong in the first place.

I integrated the server into my existing express app and had to revert the changes I made to the code to get it to work again. I guess I just fixed some symptoms and not the problem with my fix.

**Comment by AlphaHinex** [comment]
Maybe you need to update the version of `socket.io-client` too. I did similar changes as yours and it works now. See [custom signal master server](https://signalmaster.leanapp.cn/) and [source](https://github.com/AlphaHinex/signalmaster).

**Comment by fippo** [comment]
that should be fixed with #65 now

**Pull request closed without merging**
