### PR TITLE
upgrade socket.io to 1.2.1; debugging is done via env vars

### PR DESCRIPTION
**Pull request by fippo**
sync with https://github.com/HenrikJoreteg/SimpleWebRTC/pull/191

ops-note: use env variables for debug as described in http://socket.io/docs/logging-and-debugging/ instead of having it configured in the config.

### CODE REVIEW

**Comment by xenyou** [comment]
+1

**Comment by bear** [comment]
@fippo do we need to adjust documentation to point out the deprecation of older code?

**Comment by bear** [comment]
+1

**Comment by fippo** [comment]
@bear i don't see any other solution than a flag day for this. And right now it is _very_ low on my priority list. If you're interested : run your own signalmaster.

**Comment by bear** [comment]
@fippo Understood, then I would suggest adding to your PR a bump of the signalmaster version to increment the major number and then in the release notes we note that this is a backwards breaking change.

**Comment by fippo** [comment]
@bear i don't want to do that without us dogfooding on it. And that isn't going to happen soon.

**Comment by bear** [comment]
k, understand now what type and scope of this change is - withdrawing my suggestion for a version bump.

**Pull request closed without merging**
