### PR TITLE
Added the ability to use an existing express server

### PR DESCRIPTION
**Pull request by shichongrui**

### CODE REVIEW

**Comment by robschley** [comment]
Any plans to merge this PR?

**Comment by bear** [comment]
apologies for the delay in responding...

We love the idea of moving the socket handling code into sockets.js so that it's easier to add/expand the code but we really do not want to start adding each framework's server to the code base because we want it to be as generic as possible. 

Would you mind altering the PR so that it just doesn't have the express.js part? That part would be in your code base.

thanks

**Comment by shichongrui** [comment]
Updated

**Comment by bear** [comment]
thanks - let me review this and get a final +1 from another of our devs...

**Comment by felipebrahm** [comment]
@bear could you publish this to the npm registry as a new version? thanks!

**Pull request merged**
