### PR TITLE
SSL Certs

### PR DESCRIPTION
**Pull request by jloveland**
adding generate-ssl-certs and making configs for production (this just shows an example using tls/ssl)

### CODE REVIEW

**Comment by bear** [comment]
Apologies for the delay ... could you freshen this with the latest master branch and resubmit?

I want to land this before we publish to NPM - thanks

**Comment by jloveland** [comment]
@bear what do you think after I freshened?

**Comment by bear** [comment]
@jloveland I'm +1 for this, but as I don't work for &yet anymore we will have to try and get @fippo or @legastero to do the honours

**Comment by fippo** [comment]
LGTM, thanks!

 -- no npm package for this AFAIK

**Pull request merged**
