### PR TITLE
use newer .urls syntax for iceServers

### PR DESCRIPTION
**Pull request by fippo**
@xdumaine @legastero?

### CODE REVIEW

**Comment by xdumaine** [comment]
Neat. Does this have an analog for http://xmpp.org/extensions/xep-0215.html?

**Comment by fippo** [comment]
xep-0215 doesn't have an analog. Which doesn't stop stanza from optimizing things. I suspect there are some smart things the client could do when knowing that turn:<ip>:3478?transport=udp and turn:<ip>:80?transport=tcp are the same server but iirc chrome currently can not use this information.

**Comment by xdumaine** [comment]
Lgtm

**Comment by fippo** [comment]
btw: this still supports the old syntax

**Pull request merged**
